/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LopHoc;

import Check.Check;
import Khoa.IKhoaDAO;
import Khoa.Khoa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BKHN
 */
public class frmLopHoc extends javax.swing.JPanel {

    private DefaultComboBoxModel dcbm;
    private DefaultTableModel dtm;
    ArrayList<Khoa> allKhoa = null;
    ArrayList<LopHoc> allLop = null;

    /**
     * Creates new form frmLopHoc
     */
    public frmLopHoc() {
        try {
            initComponents();
            dcbm = new DefaultComboBoxModel();
            dtm = new DefaultTableModel();
            IKhoaDAO khoaDAO = (IKhoaDAO) Class.forName("Khoa.KhoaDAO").newInstance();
            allKhoa = khoaDAO.getAll();
            for (Khoa k : allKhoa) {
                dcbm.addElement(k.getMakhoa());
            }
            jcbMaKhoa.setModel(dcbm);
            dtm.addColumn("Mã Lớp");
            dtm.addColumn("Tên Tên Lớp");
            dtm.addColumn("Mã Khoa");
            dtm.addColumn("Khóa Học");
            loaddata();

        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException ex) {
            Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLop = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfMaLop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbMaKhoa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtfTenLop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfKhoaHoc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbNew = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 51, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        setPreferredSize(new java.awt.Dimension(873, 371));

        jPanel1.setBackground(new java.awt.Color(255, 51, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 51, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jtbLop = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        jtbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Tên Lớp ", "Mã Khoa", "Khóa Học"
            }
        ));
        jtbLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbLop);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel3.setLayout(new java.awt.GridLayout(2, 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mã Lớp");
        jPanel3.add(jLabel2);
        jPanel3.add(jtfMaLop);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mã Khoa");
        jPanel3.add(jLabel5);

        jcbMaKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaKhoaActionPerformed(evt);
            }
        });
        jPanel3.add(jcbMaKhoa);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên Lớp ");
        jPanel3.add(jLabel3);
        jPanel3.add(jtfTenLop);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Khóa Học");
        jPanel3.add(jLabel4);

        jtfKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKhoaHocActionPerformed(evt);
            }
        });
        jPanel3.add(jtfKhoaHoc);

        jPanel4.setBackground(new java.awt.Color(255, 51, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jbNew.setBackground(new java.awt.Color(153, 255, 204));
        jbNew.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbNew.setForeground(new java.awt.Color(0, 204, 204));
        jbNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jbNew.setText("AddNew");
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });
        jPanel4.add(jbNew);

        jbUpdate.setBackground(new java.awt.Color(204, 255, 204));
        jbUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(255, 153, 51));
        jbUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Update.png"))); // NOI18N
        jbUpdate.setText("Update");
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbUpdate);

        jbDelete.setBackground(new java.awt.Color(255, 153, 255));
        jbDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbDelete.setForeground(new java.awt.Color(153, 0, 0));
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbDelete);

        jbExit.setBackground(new java.awt.Color(204, 255, 255));
        jbExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExit.setForeground(new java.awt.Color(0, 102, 102));
        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        jbExit.setText("Reset");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbExit);

        jPanel5.setBackground(new java.awt.Color(255, 51, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN LỚP HỌC");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public frmLopHoc(JTable jtbLop) {
        this.jtbLop = jtbLop;
    }

    private void loaddata() {
        try {
            try {
                ILopHocDAO lopHocDAO = (ILopHocDAO) Class.forName("LopHoc.LopHocDAO").newInstance();
                allLop = new LopHocDAO().getAll();
                for (LopHoc lh : allLop) {
                    dtm.addRow(toObjectsData(lh));
                }
                jtbLop.setModel(dtm);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (InstantiationException ex) {
            Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private static Object[] toObjectsData(LopHoc lh) {
        Object[] objectsdata = {lh.getMalop(), lh.getTenlop(), lh.getMakhoa(), lh.getKhoahoc()};
        return objectsdata;
    }

    public boolean checkinfo() {
        Check c = new Check();
        if (!c.checkID(jtfMaLop.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập mã lớp sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfMaLop.setText("");
            jtfMaLop.requestFocus();
            return false;
        } else if (!c.checkSpace(jtfTenLop.getText()) || !c.check(jtfTenLop.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập tên lơp học sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfTenLop.setText("");
            jtfTenLop.requestFocus();
            return false;

        } else if (!c.checkSpace(jtfKhoaHoc.getText()) || !c.check(jtfKhoaHoc.getText())) {
            JOptionPane.showMessageDialog(this, "Lỗi khóa học", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfKhoaHoc.setText("");
            jtfKhoaHoc.requestFocus();
            return false;
        }
        return true;
    }
    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
        this.ResetForm();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jtfKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKhoaHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKhoaHocActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        // TODO add your handling code here:
        String malop = jtfMaLop.getText();
        String tenlop = jtfTenLop.getText();
        String khoahoc = jtfKhoaHoc.getText();
        String makhoa = allKhoa.get(jcbMaKhoa.getSelectedIndex()).getMakhoa();
        if (!checkinfo()) {
            return;
        }

        /*  if (malop == null || malop.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
            return;
        }
        if (tenlop == null || tenlop.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
            return;
        }
        if (khoahoc == null || khoahoc.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
            return;
        }*/
        LopHoc lh = new LopHoc(malop, tenlop, makhoa, khoahoc);
        LopHoc update = new LopHocDAO().updateByID(lh);
        if (update != null) {
            showAll();
        }
        jbNew.setEnabled(true);
        jbUpdate.setEnabled(false);
        jbDelete.setEnabled(false);
        jtfMaLop.setEnabled(true);
    }//GEN-LAST:event_jbUpdateActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                String malop = jtfMaLop.getText();
                new LopHocDAO().deleteLopHoc(malop);
            } catch (SQLException ex) {
                Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmLopHoc.class.getName()).log(Level.SEVERE, null, ex);
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            loaddata();
            ResetForm();
            jbNew.setEnabled(true);
            jbUpdate.setEnabled(false);
            jbDelete.setEnabled(false);
            jtfMaLop.setEnabled(true);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        // TODO add your handling code here:
        String malop = jtfMaLop.getText();
        String tenlop = jtfTenLop.getText();
        String khoahoc = jtfKhoaHoc.getText();
        String makhoa = allKhoa.get(jcbMaKhoa.getSelectedIndex()).getMakhoa();
        if (!checkinfo()) {
            return;
        }
        // if (malop == null || malop.trim().equals("")) {
        //     JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
        //    return;
        // }
        //if (tenlop == null || tenlop.trim().equals("")) {
        //    JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
        //    return;
        //}
        //if (khoahoc == null || khoahoc.trim().equals("")) {
        //    JOptionPane.showMessageDialog(null, "Lỗi Mã lớp, vui lòng kiểm tra lại");
        //    return;
        //}
        LopHoc lh = new LopHoc(malop, tenlop, makhoa, khoahoc);
        ArrayList<LopHoc> listCheck = new LopHocDAO().checkID(malop);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            jtfMaLop.setText("");
            jtfMaLop.requestFocus();
        } else {
            LopHoc insert = new LopHocDAO().addNew(lh);
            if (insert != null) {
                showAll();
            }
        }
    }//GEN-LAST:event_jbNewActionPerformed

    private void jtbLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLopMouseClicked
        // TODO add your handling code here:
        jtfMaLop.setText(jtbLop.getValueAt(jtbLop.getSelectedRow(), 0).toString());
        jtfTenLop.setText(jtbLop.getValueAt(jtbLop.getSelectedRow(), 1).toString());
        jcbMaKhoa.setSelectedItem(jtbLop.getValueAt(jtbLop.getSelectedRow(), 2).toString());
        jtfKhoaHoc.setText(jtbLop.getValueAt(jtbLop.getSelectedRow(), 3).toString());

        jbNew.setEnabled(true);
        jbUpdate.setEnabled(true);
        jbDelete.setEnabled(true);
        jtfMaLop.setEnabled(false);
    }//GEN-LAST:event_jtbLopMouseClicked

    private void jcbMaKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaKhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaKhoaActionPerformed
    public void ResetForm() {
        jtfMaLop.setText("");
        jtfTenLop.setText("");
        jtfKhoaHoc.setText("");
        jtfMaLop.requestFocus();
    }

    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        int selectedIndex = jcbMaKhoa.getSelectedIndex();
        Khoa getkhoa = allKhoa.get(selectedIndex);
        ArrayList<LopHoc> lhs = new LopHocDAO().findByIDKhoa(getkhoa.getMakhoa());
        for (LopHoc lopHoc : lhs) {
            Vector v = new Vector();
            v.add(lopHoc.getMalop());
            v.add(lopHoc.getTenlop());
            v.add(lopHoc.getMakhoa());
            v.add(lopHoc.getKhoahoc());
            dtm.addRow(v);
        }
        ResetForm();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JComboBox<String> jcbMaKhoa;
    private javax.swing.JTable jtbLop;
    private javax.swing.JTextField jtfKhoaHoc;
    private javax.swing.JTextField jtfMaLop;
    private javax.swing.JTextField jtfTenLop;
    // End of variables declaration//GEN-END:variables
}
