/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUILOGIN;

import AddUser.frmAddUser;
import BangDiem.frmBangDiem;
import BangDiem.frmTinhDiem;
import GiaoVien.frmGiaoVien;
import Khoa.frmKhoa;
import LopHoc.frmLopHoc;
import MonHoc.frmMonHoc;
import Search.Search;
import SinhVien.frmSinhVien;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author BKHN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //  this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbInputStudent = new javax.swing.JButton();
        jbInputTeacher = new javax.swing.JButton();
        jbClass = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbInputDiem = new javax.swing.JButton();
        jbtinhdiem = new javax.swing.JButton();
        jtpContent = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmiLogOff = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmiExit = new javax.swing.JMenuItem();
        jmTacVu = new javax.swing.JMenu();
        jmiAddUser = new javax.swing.JMenuItem();
        jmiNhapSV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiNhapGV = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiNhapDiem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiNhapLop = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiMonHoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiNhapKhoa = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();
        jmHoTro = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT INFORMATION SYSTEM - NGUYEN DINH QUANG - MSSV: 20146574 - LOP: CN_CNTT_01_K59 - ĐẠI HỌC BÁCH KHOA HÀ NỘI");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconbkhn.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jPanel3.setLayout(new java.awt.GridLayout(7, 1));

        jbInputStudent.setBackground(new java.awt.Color(255, 102, 0));
        jbInputStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbInputStudent.setForeground(new java.awt.Color(255, 255, 255));
        jbInputStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jbInputStudent.setText("Nhập Sinh Viên");
        jbInputStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputStudentActionPerformed(evt);
            }
        });
        jPanel3.add(jbInputStudent);

        jbInputTeacher.setBackground(new java.awt.Color(255, 255, 0));
        jbInputTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbInputTeacher.setForeground(new java.awt.Color(255, 255, 255));
        jbInputTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jbInputTeacher.setText("Nhập Giảng Viên");
        jbInputTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputTeacherActionPerformed(evt);
            }
        });
        jPanel3.add(jbInputTeacher);

        jbClass.setBackground(new java.awt.Color(255, 51, 204));
        jbClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbClass.setForeground(new java.awt.Color(255, 255, 255));
        jbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jbClass.setText("Nhập Lớp ");
        jbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClassActionPerformed(evt);
            }
        });
        jPanel3.add(jbClass);

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jButton6.setText("Nhập Khoa ");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton5.setBackground(new java.awt.Color(51, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jButton5.setText("Nhập Môn Học");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jbInputDiem.setBackground(new java.awt.Color(0, 255, 0));
        jbInputDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbInputDiem.setForeground(new java.awt.Color(255, 255, 255));
        jbInputDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jbInputDiem.setText("Nhập Điểm ");
        jbInputDiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputDiemActionPerformed(evt);
            }
        });
        jPanel3.add(jbInputDiem);

        jbtinhdiem.setBackground(new java.awt.Color(255, 0, 0));
        jbtinhdiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtinhdiem.setForeground(new java.awt.Color(255, 255, 255));
        jbtinhdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/login.png"))); // NOI18N
        jbtinhdiem.setText("Điểm Sinh Viên");
        jbtinhdiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtinhdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtinhdiemActionPerformed(evt);
            }
        });
        jPanel3.add(jbtinhdiem);

        jtpContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jtpContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.white));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2016321 BK2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, Short.MAX_VALUE)
        );

        jtpContent.addTab("Main", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/banner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtpContent)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtpContent)))
        );

        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/system.png"))); // NOI18N
        jmHeThong.setText("System");

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logoff.png"))); // NOI18N
        jmiLogOff.setText("Log Off");
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);
        jmHeThong.add(jSeparator7);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar1.add(jmHeThong);

        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menutask.png"))); // NOI18N
        jmTacVu.setText("Task");

        jmiAddUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmiAddUser.setForeground(new java.awt.Color(0, 0, 204));
        jmiAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plusitem.png"))); // NOI18N
        jmiAddUser.setText("Tạo Mới Người Dùng");
        jmiAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddUserActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiAddUser);

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapSV.setForeground(new java.awt.Color(0, 0, 204));
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiNhapSV.setText("Nhập Sinh Viên");
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);
        jmTacVu.add(jSeparator2);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapGV.setForeground(new java.awt.Color(0, 0, 204));
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiNhapGV.setText("Nhập Giảng Viên");
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);
        jmTacVu.add(jSeparator3);

        jmiNhapDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapDiem.setForeground(new java.awt.Color(0, 0, 204));
        jmiNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiNhapDiem.setText("Nhập Điểm ");
        jmiNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapDiem);
        jmTacVu.add(jSeparator4);

        jmiNhapLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapLop.setForeground(new java.awt.Color(0, 0, 204));
        jmiNhapLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiNhapLop.setText("Nhập Lớp");
        jmiNhapLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapLopActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapLop);
        jmTacVu.add(jSeparator5);

        jmiMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jmiMonHoc.setForeground(new java.awt.Color(0, 0, 204));
        jmiMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiMonHoc.setText("Nhập Môn Học");
        jmiMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMonHocActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiMonHoc);
        jmTacVu.add(jSeparator6);

        jmiNhapKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapKhoa.setForeground(new java.awt.Color(0, 0, 204));
        jmiNhapKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new.png"))); // NOI18N
        jmiNhapKhoa.setText("Nhập Khoa");
        jmiNhapKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapKhoaActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapKhoa);

        jMenuBar1.add(jmTacVu);

        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        jmTimKiem.setText("Search");
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmTimKiem);

        jmHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Contact.png"))); // NOI18N
        jmHoTro.setText("About Us");
        jmHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHoTroMouseClicked(evt);
            }
        });
        jmHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHoTroActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHoTro);

        jmHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/help.png"))); // NOI18N
        jmHelp.setText("Help");
        jmHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHelpMouseClicked(evt);
            }
        });
        jmHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        // TODO add your handling code here:
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmiNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemActionPerformed
        // TODO add your handling code here:
        frmBangDiem bangDiem = new frmBangDiem();
        jtpContent.removeAll();
        jtpContent.add("Bảng Điểm", bangDiem);
    }//GEN-LAST:event_jmiNhapDiemActionPerformed

    private void jbInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputStudentActionPerformed
        // TODO add your handling code here:
        frmSinhVien sinhVien = new frmSinhVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Sinh Viên", sinhVien);
    }//GEN-LAST:event_jbInputStudentActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        // TODO add your handling code here:
        frmGiaoVien giaoVien = new frmGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Giảng Viên", giaoVien);

    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmiNhapKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapKhoaActionPerformed
        // TODO add your handling code here:
        frmKhoa khoa = new frmKhoa();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Khoa Viện", khoa);
    }//GEN-LAST:event_jmiNhapKhoaActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
        // TODO add your handling code here:
        frmSinhVien sinhVien = new frmSinhVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Sinh Viên", sinhVien);

    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jbInputTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputTeacherActionPerformed
        // TODO add your handling code here:
        frmGiaoVien giaoVien = new frmGiaoVien();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Giảng Viên", giaoVien);
    }//GEN-LAST:event_jbInputTeacherActionPerformed

    private void jbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClassActionPerformed
        // TODO add your handling code here:
        frmLopHoc lophoc = new frmLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jbClassActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        frmKhoa khoa = new frmKhoa();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Khoa Viện", khoa);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frmMonHoc monhoc = new frmMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jmiNhapLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapLopActionPerformed
        // TODO add your handling code here:
        frmLopHoc lophoc = new frmLopHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jmiNhapLopActionPerformed

    private void jmiMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMonHocActionPerformed
        // TODO add your handling code here:
        frmMonHoc monhoc = new frmMonHoc();
        jtpContent.removeAll();
        jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jmiMonHocActionPerformed

    private void jbInputDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputDiemActionPerformed
        // TODO add your handling code here:
        frmBangDiem bangDiem = new frmBangDiem();
        jtpContent.removeAll();
        jtpContent.add("Bảng Điểm", bangDiem);
    }//GEN-LAST:event_jbInputDiemActionPerformed

    private void jbtinhdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtinhdiemActionPerformed
        // TODO add your handling code here:
        frmTinhDiem tinhDiem = new frmTinhDiem();
        jtpContent.removeAll();
        jtpContent.add("Tính Điểm", tinhDiem);

    }//GEN-LAST:event_jbtinhdiemActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        MainLogin mainLogin = new MainLogin();
        mainLogin.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHoTroMouseClicked
        // TODO add your handling code here:
        AboutMe aboutMe = new AboutMe();
        aboutMe.setVisible(true);

    }//GEN-LAST:event_jmHoTroMouseClicked

    private void jmHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHelpMouseClicked
        // TODO add your handling code here:
       String fileName = "D:\\New folder\\QuanLySinhVien\\src\\Help\\HelpTutorial.chm";
        String[] commands = {"cmd", "/c", fileName};
        try {
            Runtime.getRuntime().exec(commands);
            //Runtime.getRuntime().exec("D:\New folder\QuanLySinhVien\src\Help\HelpTutorial.chm");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jmHelpMouseClicked

    private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        // TODO add your handling code here:
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemMouseClicked

    private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        // TODO add your handling code here:
        Search timkiem = new Search();
        jtpContent.removeAll();
        jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemActionPerformed

    private void jmiAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddUserActionPerformed
        // TODO add your handling code here:
        frmAddUser addUser = new frmAddUser();
        jtpContent.removeAll();
        jtpContent.add("Tạo User", addUser);
    }//GEN-LAST:event_jmiAddUserActionPerformed

    private void jmHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHelpActionPerformed

    private void jmHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHoTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHoTroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JButton jbClass;
    private javax.swing.JButton jbInputDiem;
    private javax.swing.JButton jbInputStudent;
    private javax.swing.JButton jbInputTeacher;
    private javax.swing.JButton jbtinhdiem;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmHoTro;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiAddUser;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiMonHoc;
    private javax.swing.JMenuItem jmiNhapDiem;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapKhoa;
    private javax.swing.JMenuItem jmiNhapLop;
    private javax.swing.JMenuItem jmiNhapSV;
    private javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables

}
